version: "3"

networks:
  d.net:
    driver: bridge

services:
  web.backoffice:
    image: elrhomariyounes/testbackoffice
    ports:
      - "19380:80"
    networks:
      - d.net
    links:
      - api.backoffice:api.backoffice.local
    depends_on:
      - api.backoffice

  api.backoffice:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.backoffice.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "19080:80"
      - "19043:443"
    volumes:
      - ./backoffice_api/public:/var/www/public
      - ./backoffice_api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - d.net
    links :
      - mysql:db

  api.mobile:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.mobile.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "19180:80"
      - "19143:443"
    volumes:
      - ./mobile_api/public:/var/www/public
      - ./mobile_api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - d.net
    links:
      - mysql:db

  api.player:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.player.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - "19280:80"
      - "19243:443"
    volumes:
      - ./player_api/public:/var/www/public
      - ./player_api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - d.net
    links:
      - mysql:db

  web.player:
    image: elrhomariyounes/testplayer
    ports:
      - "19480:80"
    networks:
      - d.net
    links:
      - api.player:api.player.local
    depends_on:
      - api.player

  #############################
  # mysql + phpmyadmin
  #############################


  mysql:
    #    image: mysql:5.6
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=geoquizz
      - MYSQL_PASSWORD=geoquizz
      - MYSQL_DATABASE=geoquizz
    ports:
      - "3307:3306"
    volumes :
      - ./backoffice_api/sql:/var/sql
    networks:
      - d.net

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - d.net
    links:
      - mysql:db

